# PHP module (mod_php) - Apache 2.4 syntax
<IfModule mpm_prefork_module>
  LoadModule php5_module modules/libphp5.so
</IfModule>
<IfModule !mpm_prefork_module>
  LoadModule php5_module modules/libphp5-zts.so
</IfModule>
