ARG os=8.10.20240528
FROM aursu/rpmbuild:${os}-build

USER root
RUN dnf -y install \
        libXpm-devel \
        libvpx-devel \
        aspell-devel \
        enchant-devel \
        firebird-devel \
        freetds-devel \
        gmp-devel \
        libc-client-devel \
        libmcrypt-devel \
        cyrus-sasl-devel \
        freetype-devel \
        gdbm-devel \
        httpd-devel \
        krb5-devel \
        libacl-devel \
        libcurl-devel \
        libedit-devel \
        libdb-devel \
        libjpeg-turbo-devel \
        libpng-devel \
        libtidy-devel \
        libtool-ltdl-devel \
        libxml2-devel \
        libxslt-devel \
        openldap-devel \
        pam-devel \
        pcre-devel \
        perl \
        postgresql-devel \
        postfix \
        recode-devel \
        t1lib-devel \
        tokyocabinet-devel \
        sqlite-devel \
        systemd-devel \
        systemtap-sdt-devel \
        unixODBC-devel \
    && dnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*

RUN dnf -y --enablerepo=bintray-custom install \
        compat-openssl10-devel \
        libicu-devel \
        mysql-devel-5.1.60 \
    && dnf clean all && rm -rf /var/cache/dnf /var/lib/rpm/__db*