services:
  rocky9php56:
    volumes:
      - rpm9rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL9
  rocky8php56:
    volumes:
      - rpm8rocky:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $RL8

volumes:
  rpm9rocky:
    name: rpm9rocky
  rpm8rocky:
    name: rpm8rocky
