services:
  rocky8run:
    build:
      context: .
      args:
        rocky: $RL8
    image: "ghcr.io/rpmbsys/php56build:${RL8TAG}-${RUNTAG}"
  rocky8httpd:
    build:
      context: .
      dockerfile: Dockerfile.httpd
      args:
        rocky: $RL8
    image: "ghcr.io/rpmbsys/php56build:${RL8TAG}-httpd-${RUNTAG}"